language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "nightly"  # nightly build
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest
 
jobs:
  include:
      name: Deploy to GitHub Pages
      script: make html
      deploy:
         provider: pages # deploy on github pages
         skip_cleanup: true
         github_token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
         on:
            branch: master
         local_dir: build/html

