language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.7-dev"  # 3.7 development branch
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest
 
 
stages:
  - build and test
  - deploy 
jobs:
  include:
    - stage: build and test # This stage builds and lints in parallel
      name: Build
      script: make html # build the docs
      skip-cleanup: true
    - stage: deploy
      name: Deploy to GitHub Pages
      if: (NOT type IN (pull_request)) AND (branch = master) # only deploy if merging on master
      script: make html
      deploy:
         provider: pages # deploy on github pages
         skip_cleanup: true
         local_dir: build/html
  
