language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest
  
jobs:
  include:
    name: Build and deploy docs
    script: cd docs && make html && make html
    deploy:
      provider: pages
      skip-cleanup: true
      keep-history: true
      on:
        branch: master
      github-token: $SPHINX_DOCS_token
      local-dir: docs/build/html
      committer-from-gh: true
