language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest
 
jobs:
  include:
      name: Deploy to GitHub Pages
      script: cd docs/ && make html
      deploy:
         provider: pages # deploy on github pages
         skip_cleanup: true
         on:
            branch: master
         local_dir: build/html

